---
title: "Tropho-biomes"
author: "C Wall"
date: '2022-07-21'
output:
  html_document:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '4'
---

```{r setup chunk, setup, include = FALSE, cache=FALSE, message=FALSE, warning=FALSE}
if (!require('knitr')) install.packages('knitr'); library('knitr')
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.align='center')

# load packages
if (!require("pacman")) install.packages("pacman") # for rapid install if not in library

# use pacman to load all the packages you are missing!
pacman::p_load('knitr', 'ggridges', 'lme4', 'lmerTest', 'tidyverse', 'magrittr', 'effects', 'plyr',
               'dplyr', 'plotrix', 'car',"gridExtra", "cowplot", "tools", "remotes", "cutoff", "bbmle")
```

```{r YSI data}
YSI<-read.csv("data/YSI.csv")

# fix date
YSI$Date<-as.character(YSI$Date)
YSI$Date<-as.POSIXct(YSI$Date, format="%m/%d/%y")
YSI$Date<-as.Date(YSI$Date, format="%m/%d/%Y")


YSI$TB<-interaction(YSI$Trophic.type, YSI$Plankton.pres.abs)

YSI$TB<-recode_factor(YSI$TB, "Low.abs -" = "L-", 
                              "High.abs -" = "H-",
                              "Plant.abs -" = "LP-",
                              "Low.pres +" = "L+", 
                              "High.pres +" = "H+",
                              "Plant.pres +" = "LP+")

YSI$TB<-factor(YSI$TB, levels=c("L+", "L-", "H+", "H-", "LP+", "LP-"))


####### Time 0.5 change in O2 ################

#separate time points
YSI.T05<- YSI[(YSI$Time.point=="T0.5"),]

#calculate NEP for T0.5
T05.Prod<-YSI.T05[(YSI.T05$Date == "2022-07-12"),] # dawn and dusk for 12h period
T05.Dawn1<-T05.Prod[(T05.Prod$Dawn..Dusk == "dawn"),] # dawn-1 measurements
T05.Dusk2<-T05.Prod[(T05.Prod$Dawn..Dusk == "dusk"),] # dusk-2 measurements

T05.Dusk1<-YSI.T05[(YSI.T05$Date == "2022-07-11"),] # dusk-1 measurements, previous PM

# make new dataframe
T05.O2<-(T05.Dawn1[,c(1,3:8,15,10)]) 
T05.O2$dusk1<-T05.Dusk1$DO..percent
T05.O2$dawn1<-T05.Dawn1$DO..percent
T05.O2$dusk2<-T05.Dusk2$DO..percent


# NER = dusk1 - dawn1 (PM to AM, O2 change of day 1)
# NEP = dusk2 - dawn1 (PM to AM, O2 change of day 2)

T05.O2<- mutate(T05.O2, 
                NEP=dusk2 - dawn1,
                NER=dawn1 - dusk1) 



####### Time 1 change in O2 ################

#separate time points
YSI.T1<- YSI[(YSI$Time.point=="T1"),]

#calculate NEP for T1
T1.Prod<-YSI.T1[(YSI.T1$Date == "2022-07-21"),] # dawn and dusk for 12h period
T1.Dawn1<-T1.Prod[(T1.Prod$Dawn..Dusk == "dawn"),] # dawn-1 measurements
T1.Dusk2<-T1.Prod[(T1.Prod$Dawn..Dusk == "dusk"),] # dusk-2 measurements

T1.Dusk1<-YSI.T1[(YSI.T1$Date == "2022-07-20"),] # dusk-1 measurements, previous PM

# make new dataframe
T1.O2<-(T1.Dawn1[,c(1,3:8,15,10)]) 
T1.O2$dusk1<-T1.Dusk1$DO..percent
T1.O2$dawn1<-T1.Dawn1$DO..percent
T1.O2$dusk2<-T1.Dusk2$DO..percent


# NER = dusk1 - dawn1 (PM to AM, O2 change of day 1)
# NEP = dusk2 - dawn1 (PM to AM, O2 change of day 2)

T1.O2<- mutate(T1.O2, 
                NEP=dusk2 - dawn1,
                NER=dawn1 - dusk1) 



####### Time 2 change in O2 ################

#separate time points
YSI.T2<- YSI[(YSI$Time.point=="T2"),]

#calculate NEP for T2
T2.Prod<-YSI.T2[(YSI.T2$Date == "2022-07-29"),] # dawn and dusk for 12h period
T2.Dawn1<-T2.Prod[(T2.Prod$Dawn..Dusk == "dawn"),] # dawn-1 measurements
T2.Dusk2<-T2.Prod[(T2.Prod$Dawn..Dusk == "dusk"),] # dusk-2 measurements

T2.Dusk1<-YSI.T2[(YSI.T2$Date == "2022-07-28"),] # dusk-1 measurements, previous PM

# make new dataframe
T2.O2<-(T2.Dawn1[,c(1,3:8,15,10)]) 
T2.O2$dusk1<-T2.Dusk1$DO..percent
T2.O2$dawn1<-T2.Dawn1$DO..percent
T2.O2$dusk2<-T2.Dusk2$DO..percent


# NER = dusk1 - dawn1 (PM to AM, O2 change of day 1)
# NEP = dusk2 - dawn1 (PM to AM, O2 change of day 2)

T2.O2<- mutate(T2.O2, 
                NEP=dusk2 - dawn1,
                NER=dawn1 - dusk1) 


####### Time 3 change in O2 ################
#### * note that new YSI used and measurements were taken as *dawn, dusk, dawn* this time only * ####

#separate time points
YSI.T3<- YSI[(YSI$Time.point=="T3"),]

#calculate NEP for T3
T3.Prod<-YSI.T3[(YSI.T3$Date == "2022-08-17"),] # dawn and dusk for 12h period
T3.Dawn1<-T3.Prod[(T3.Prod$Dawn..Dusk == "dawn"),] # dawn-1 measurements
T3.Dusk1<-T3.Prod[(T3.Prod$Dawn..Dusk == "dusk"),] # dusk-1 measurements

T3.Dawn2<-YSI.T3[(YSI.T3$Date == "2022-08-18"),] # dawn-1 measurements, next PM

# make new dataframe
T3.O2<-(T3.Dawn1[,c(1,3:8,15,10)]) 
T3.O2$dawn1<-T3.Dawn1$DO..percent
T3.O2$dusk1<-T3.Dusk1$DO..percent
T3.O2$dawn2<-T3.Dawn2$DO..percent


# NER = dusk1 - dawn1 (PM to AM, O2 change of day 1)
# NEP = dusk2 - dawn1 (PM to AM, O2 change of day 2)

T3.O2<- mutate(T3.O2, 
                NEP= dusk1 - dawn1,
                NER= dawn2 - dusk1) 
 
```

Time 0.5 plot
```{r T0.5 DO plot}
########## 
Fig.formatting<-(theme_classic()) +
  theme(text=element_text(size=10),
        axis.line=element_blank(),
        legend.text.align = 0,
        legend.text=element_text(size=10),
        #legend.title = element_blank(),
        panel.border = element_rect(fill=NA, colour = "black", size=1),
        aspect.ratio=1, 
        axis.ticks.length=unit(0.25, "cm"),
        axis.text.y=element_text(
          margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=10), 
        axis.text.x=element_text(
          margin=unit(c(0.5, 0.5, 0.5, 0.5), "cm"), colour="black", size=8)) +
  theme(legend.key.size = unit(0.4, "cm")) +
  theme(aspect.ratio=1.3) +
  theme(panel.spacing=unit(c(0, 0, 0, 0), "cm"))

#########################################################
############################################################################
###############################################################################################

# Time 0.5 plots
#################
T05.O2$Trophic.type<-factor(T05.O2$Trophic.type, levels=c("Low", "High", "Plant"))

T05.PM1<-ggplot(T05.O2, aes(x=TB, y=dusk1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T05.dusk1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T05.AM1<-ggplot(T05.O2, aes(x=TB, y=dawn1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T05.dawn1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T05.PM2<-ggplot(T05.O2, aes(x=TB, y=dusk2, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T05.dusk2")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

extract.legend <- get_legend(
  # create some space to the left of the legend
  T05.PM1 + theme(legend.box.margin = margin(0, 0, 0, 10)))

O2.T05<-plot_grid(
  T05.PM1+ theme(legend.position = "none"), 
  T05.AM1+ theme(legend.position = "none"), 
  T05.PM2+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,3), ncol=4)

ggsave("figures/O2.T05.pdf", height=5, width=9)

#################################
############################################
# net ecosystem production and respiration

#Time 0.5 NEP
NEP.T05<-ggplot(T05.O2, aes(x=TB, y=NEP, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Production (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-20, 50)) +
  xlab("Trophic Type") +
  Fig.formatting


#Time 0.5 NER
NER.T05<-ggplot(T05.O2, aes(x=TB, y=NER, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Respiration (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-40, 20)) +
  xlab("Trophic Type") +
  Fig.formatting


O2.change.T05<-plot_grid(
  NEP.T05+ theme(legend.position = "none") + ggtitle("Time 0.5"), 
  NER.T05+ theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/O2.change.T05.pdf", height=5, width=8)

```

Time 1 plot
```{r T1 DO plot}
# total oxygen % plot for the 3 time points (dusk-dawn-dusk)
# Time 1 plots
#################
T1.O2$Trophic.type<-factor(T1.O2$Trophic.type, levels=c("Low", "High", "Plant"))

T1.PM1<-ggplot(T1.O2, aes(x=TB, y=dusk1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T1.dusk1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T1.AM1<-ggplot(T1.O2, aes(x=TB, y=dawn1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T1.dawn1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T1.PM2<-ggplot(T1.O2, aes(x=TB, y=dusk2, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T1.dusk2")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

extract.legend <- get_legend(
  # create some space to the left of the legend
  T1.PM1 + theme(legend.box.margin = margin(0, 0, 0, 10)))

O2.T1<-plot_grid(
  T1.PM1+ theme(legend.position = "none"), 
  T1.AM1+ theme(legend.position = "none"), 
  T1.PM2+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,3), ncol=4)

ggsave("figures/O2.T1.pdf", height=5, width=9)

#################################
############################################
# net ecosystem production and respiration

#Time1 NEP
NEP.T1<-ggplot(T1.O2, aes(x=TB, y=NEP, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Production (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-20, 50)) +
  ggtitle("T1.NEP")+
  xlab("Trophic Type") +
  Fig.formatting


#Time1 NER
NER.T1<-ggplot(T1.O2, aes(x=TB, y=NER, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Respiration (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-40, 20)) +
  ggtitle("T1.NER")+
  xlab("Trophic Type") +
  Fig.formatting


O2.change.T1<-plot_grid(
  NEP.T1+ theme(legend.position = "none") + ggtitle("Time 1"), 
  NER.T1+ theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/O2.change.T1.pdf", height=5, width=8)

```

Time 2 plot
```{r T2 DO plots}
# total oxygen % plot for the 3 time points (dusk-dawn-dusk)
# Time 0.5 plots
#################
T2.O2$Trophic.type<-factor(T2.O2$Trophic.type, levels=c("Low", "High", "Plant"))

T2.PM1<-ggplot(T2.O2, aes(x=TB, y=dusk1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T2.dusk1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T2.AM1<-ggplot(T2.O2, aes(x=TB, y=dawn1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T2.dawn1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T2.PM2<-ggplot(T2.O2, aes(x=TB, y=dusk2, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T2.dusk2")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

extract.legend <- get_legend(
  # create some space to the left of the legend
  T2.PM1 + theme(legend.box.margin = margin(0, 0, 0, 10)))

O2.T2<-plot_grid(
  T2.PM1+ theme(legend.position = "none"), 
  T2.AM1+ theme(legend.position = "none"), 
  T2.PM2+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,3), ncol=4)

ggsave("figures/O2.T2.pdf", height=5, width=9)

#################################
############################################
# net ecosystem production and respiration

#Time1 NEP
NEP.T2<-ggplot(T2.O2, aes(x=TB, y=NEP, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Production (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-20, 50)) +
  ggtitle("T2.NEP")+
  xlab("Trophic Type") +
  Fig.formatting


#Time1 NER
NER.T2<-ggplot(T2.O2, aes(x=TB, y=NER, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Respiration (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-40, 20)) +
  ggtitle("T2.NER")+
  xlab("Trophic Type") +
  Fig.formatting


O2.change.T2<-plot_grid(
  NEP.T2+ theme(legend.position = "none") + ggtitle("Time 2"), 
  NER.T2+ theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/O2.change.T2.pdf", height=5, width=8)

```

Time 3 plot
```{r T3 DO plots}
# total oxygen % plot for the 3 time points (dawn-dusk-dawn, this time only
# Time 3 plots
#################
T3.O2$Trophic.type<-factor(T3.O2$Trophic.type, levels=c("Low", "High", "Plant"))

T3.AM1<-ggplot(T3.O2, aes(x=TB, y=dawn1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T3.dawn1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T3.PM1<-ggplot(T3.O2, aes(x=TB, y=dusk1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T3.dusk1")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

T3.AM2<-ggplot(T3.O2, aes(x=TB, y=dawn1, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ggtitle("T3.dawn2")+
  ylab(expression(paste("O"[2],"%"))) +
  coord_cartesian(ylim=c(0, 140)) +
  xlab("Trophic Type") +
  Fig.formatting

extract.legend <- get_legend(
  # create some space to the left of the legend
  T3.PM1 + theme(legend.box.margin = margin(0, 0, 0, 10)))

O2.T3<-plot_grid(
  T3.AM1+ theme(legend.position = "none"), 
  T3.PM1+ theme(legend.position = "none"), 
  T3.AM2+ theme(legend.position = "none"),
  extract.legend, 
  rel_widths = c(8,8,8,3), ncol=4)

ggsave("figures/O2.T3.pdf", height=5, width=9)

#################################
############################################
# net ecosystem production and respiration

#Time1 NEP
NEP.T3<-ggplot(T3.O2, aes(x=TB, y=NEP, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Production (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-20, 50)) +
  ggtitle("T3.NEP")+
  xlab("Trophic Type") +
  Fig.formatting


#Time1 NER
NER.T3<-ggplot(T3.O2, aes(x=TB, y=NER, color=Trophic.type)) + 
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  geom_hline(yintercept=0, linetype="longdash", color = "gray") +
  ylab(expression(paste("Net Respiration (", Delta, "O"[2],"%)"))) +
  coord_cartesian(ylim=c(-40, 20)) +
  ggtitle("T3.NER")+
  xlab("Trophic Type") +
  Fig.formatting


O2.change.T3<-plot_grid(
  NEP.T3+ theme(legend.position = "none") + ggtitle("Time 3"), 
  NER.T3+ theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,3), ncol=3)

ggsave("figures/O2.change.T3.pdf", height=5, width=8)

```

```{r all DO together}
O2.TB<-plot_grid(
  O2.T05 + theme(legend.position = "none") + ggtitle("Time 0.5"),
  O2.T1 + theme(legend.position = "none") + ggtitle("Time 1"),
  O2.T2 + theme(legend.position = "none") + ggtitle("Time 2"),
  O2.T3 + theme(legend.position = "none") + ggtitle("Time 3"),
  rel_widths = c(8,8,8,8), ncol=1)

ggsave("figures/O2.TB.pdf", height=10, width=7)

NEP.NER.TB<-plot_grid(
  NEP.T05 + theme(legend.position = "none") + ggtitle("NEP: Time 0.5"),
  NEP.T1 + theme(legend.position = "none") + ggtitle("Time 1"),
  NEP.T2 + theme(legend.position = "none") + ggtitle("Time 2"),
  NEP.T3 + theme(legend.position = "none") + ggtitle("Time 3"),
  extract.legend,
  
  NER.T05 + theme(legend.position = "none") + ggtitle("NER"),
  NER.T1 + theme(legend.position = "none") + ggtitle(""),
  NER.T2 + theme(legend.position = "none") + ggtitle(""),
  NER.T3 + theme(legend.position = "none") + ggtitle(""),
  extract.legend, 
  rel_widths = c(8,8,8,8,3), ncol=5)

ggsave("figures/NEP.NER.TB.pdf", height=7, width=10)
```
 
 
### Nutrients and Chlorophyll  

First pre-process data for chlorophyll, TN, TP, DOC.
```{r pre-process}
# process to get mean values
raw.chl<-read.csv("data/chlorophyll_TrophBio.csv")
raw.chl<-na.omit(raw.chl) # remove NAs
raw.chl$mean.chl<-((raw.chl$chl.1.ug..L + raw.chl$chl.2.ug..L)/2) - 0.01 # make average, subtract blank of 0.01

# add chla mean to TNTP
nutr<-read.csv("data/TNTPTC.csv")

make.fac<-c("Project.Name", "Time.point", "Nutrients", "Trophic.type", "Plankton.pres.abs", "Tank")
nutr[make.fac] <- lapply(nutr[make.fac], factor) # make all these factors

TB.nutr<-nutr[(nutr$Project.Name=="Trophobiomes"),] # <<<<< just the water nutrient data
TB.stock<-nutr[(nutr$Project.Name=="Nutrient.stock"),] # <<<< just nutrient stock data

# add in chlorophyll to TB.nutr
TB.nutr$mean.chl<- raw.chl$mean.chl

# new dataframe with the TNTP and chla together for all time periods
water.char<-TB.nutr

# make interaction
water.char$TB<-interaction(water.char$Trophic.type, water.char$Plankton.pres.abs)

#rename columns
colnames(water.char)[colnames(water.char) == 'TDP..ug.L'] <- 'TDP'
colnames(water.char)[colnames(water.char) == 'TDN..ug.L'] <- 'TDN'
colnames(water.char)[colnames(water.char) == 'DOC..mg.L'] <- 'DOC'

water.char$TB<-recode_factor(water.char$TB, "Low.abs -" = "L-", 
                              "High.abs -" = "H-",
                              "Plant.abs -" = "LP-",
                              "Low.pres +" = "L+", 
                              "High.pres +" = "H+",
                              "Plant.pres +" = "LP+")

water.char$TB<-factor(water.char$TB, levels=c("L+", "L-", "H+", "H-", "LP+", "LP-"))

water.char$Trophic.type<- factor(water.char$Trophic.type, levels=c("Low", "High", "Plant"))

```

#### Chlorophll  
```{r chlorophyll}
chl<-water.char # for ease here, but same df

T05.chl<-ggplot(chl[(chl$Time.point=="T0.5"),], aes(x=TB, y=mean.chl, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T05")+
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 40)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T1.chl<-ggplot(chl[(chl$Time.point=="T1"),], aes(x=TB, y=mean.chl, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T1")+
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 40)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T2.chl<-ggplot(chl[(chl$Time.point=="T2"),], aes(x=TB, y=mean.chl, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T2")+
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 40)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T3.chl<-ggplot(chl[(chl$Time.point=="T3"),], aes(x=TB, y=mean.chl, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T3")+
  ylab(expression(paste("chlorophyll", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 40)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

extract.legend.chl <- get_legend(
  # create some space to the left of the legend
  T3.chl + theme(legend.box.margin = margin(0, 0, 0, 10)))


chl.TB<-plot_grid(
  T05.chl+ theme(legend.position = "none") + ggtitle("Time 0.5"),
  T1.chl+ theme(legend.position = "none") + ggtitle("Time 1"),
  T2.chl+ theme(legend.position = "none") + ggtitle("Time 2"), 
  T3.chl+ theme(legend.position = "none") + ggtitle("Time 3"),
  extract.legend.chl, 
  rel_widths = c(8,8,8,8, 3), ncol=5)

ggsave("figures/chl.TB.pdf", height=5, width=12)

```

#### TN-TP-DOC

Total dissolved nitrogen (TDN)
```{r TN}

T05.TN<-ggplot(water.char[(water.char$Time.point=="T0.5"),], aes(x=TB, y=TDN, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T05")+
  ylab(expression(paste("TDN", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 1200)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T1.TN<-ggplot(water.char[(water.char$Time.point=="T1"),], aes(x=TB, y=TDN, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T1")+
  ylab(expression(paste("TDN", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 1200)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T2.TN<-ggplot(water.char[(water.char$Time.point=="T2"),], aes(x=TB, y=TDN, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T2")+
  ylab(expression(paste("TDN", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 1200)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T3.TN<-ggplot(water.char[(water.char$Time.point=="T3"),], aes(x=TB, y=TDN, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T3")+
  ylab(expression(paste("TDN", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 1200)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

extract.legend.TN <- get_legend(
  # create some space to the left of the legend
  T3.TN + theme(legend.box.margin = margin(0, 0, 0, 10)))


TN.TB<-plot_grid(
  T05.TN+ theme(legend.position = "none") + ggtitle("Time 0.5"),
  T1.TN+ theme(legend.position = "none") + ggtitle("Time 1"),
  T2.TN+ theme(legend.position = "none") + ggtitle("Time 2"), 
  T3.TN+ theme(legend.position = "none") + ggtitle("Time 3"),
  extract.legend.TN, 
  rel_widths = c(8,8,8,8, 3), ncol=5)

ggsave("figures/TN.TB.pdf", height=5, width=12)

```

Total dissolved phosphorus (TDP)
```{r TDP}

T05.TP<-ggplot(water.char[(water.char$Time.point=="T0.5"),], aes(x=TB, y=TDP, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T05")+
  ylab(expression(paste("TDP", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 500)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T1.TP<-ggplot(water.char[(water.char$Time.point=="T1"),], aes(x=TB, y=TDP, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T1")+
  ylab(expression(paste("TDP", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 500)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T2.TP<-ggplot(water.char[(water.char$Time.point=="T2"),], aes(x=TB, y=TDP, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T2")+
  ylab(expression(paste("TDP", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 500)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T3.TP<-ggplot(water.char[(water.char$Time.point=="T3"),], aes(x=TB, y=TDP, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T3")+
  ylab(expression(paste("TDP", ~(mu*g~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 500)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

extract.legend.TP <- get_legend(
  # create some space to the left of the legend
  T3.TP + theme(legend.box.margin = margin(0, 0, 0, 10)))


TP.TB<-plot_grid(
  T05.TP+ theme(legend.position = "none") + ggtitle("Time 0.5"),
  T1.TP+ theme(legend.position = "none") + ggtitle("Time 1"),
  T2.TP+ theme(legend.position = "none") + ggtitle("Time 2"), 
  T3.TP+ theme(legend.position = "none") + ggtitle("Time 3"),
  extract.legend.TP, 
  rel_widths = c(8,8,8,8, 3), ncol=5)

ggsave("figures/TP.TB.pdf", height=5, width=12)

```

Dissolved organic carbon (DOC)
```{r DOC}

T05.DOC<-ggplot(water.char[(water.char$Time.point=="T0.5"),], aes(x=TB, y=DOC, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T05")+
  ylab(expression(paste("DOC", ~(mg~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 25)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T1.DOC<-ggplot(water.char[(water.char$Time.point=="T1"),], aes(x=TB, y=DOC, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T1")+
  ylab(expression(paste("DOC", ~(mg~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 25)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T2.DOC<-ggplot(water.char[(water.char$Time.point=="T2"),], aes(x=TB, y=DOC, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T2")+
  ylab(expression(paste("DOC", ~(mg~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 25)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

T3.DOC<-ggplot(water.char[(water.char$Time.point=="T3"),], aes(x=TB, y=DOC, color=Trophic.type)) +
  geom_boxplot() +
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  scale_color_manual(values = c("lightskyblue", "palegreen3", "lightsalmon3")) +
  ggtitle("T3")+
  ylab(expression(paste("DOC", ~(mg~L^-1), sep=""))) +
  coord_cartesian(ylim=c(0, 25)) +
  xlab("Trophic/Plankton") +
  Fig.formatting

extract.legend.DOC <- get_legend(
  # create some space to the left of the legend
  T3.DOC + theme(legend.box.margin = margin(0, 0, 0, 10)))


DOC.TB<-plot_grid(
  T05.DOC+ theme(legend.position = "none") + ggtitle("Time 0.5"),
  T1.DOC+ theme(legend.position = "none") + ggtitle("Time 1"),
  T2.DOC+ theme(legend.position = "none") + ggtitle("Time 2"), 
  T3.DOC+ theme(legend.position = "none") + ggtitle("Time 3"),
  extract.legend.TP, 
  rel_widths = c(8,8,8,8, 3), ncol=5)

ggsave("figures/DOC.TB.pdf", height=5, width=12)

```

```{r pool nutr}

pool.plot<-plot_grid(
  TN.TB,
  TP.TB,
  DOC.TB,
  chl.TB, ncol=1, nrow=4)

ggsave("figures/TN.TP.DOC.pdf", height=15, width=12)

```


### Bottle Incubation   
```{r}
inc<-read.csv("data/bottle_exp_survival.csv")
inc<-drop_na(inc)


inc$Inoc.treatment<- factor(inc$Inoc.treatment, levels=c("L+", "L-", "H+", "H-", "LP+", "LP-"))
inc$Inoc.plank.nutr.source<- factor(inc$Inoc.plank.nutr.source, levels=c("L+", "H+", "LP+"))

survival<-ggplot(inc, aes(y=individuals, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("number of individuals")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

ggsave("figures/survival.pdf", height=5, width=7)


#### run a model, sqrt transform survival
mod<-lm(sqrt(individuals)~ Inoc.treatment*Inoc.plank.nutr.source, data=inc)
Anova(mod, type=2)

posthoc<-emmeans(mod, ~ Inoc.plank.nutr.source |Inoc.treatment)
multcomp::cld(posthoc, Letters=letters)

posthoc<-emmeans(mod, ~ Inoc.plank.nutr.source)
multcomp::cld(posthoc, Letters=letters)

posthoc<-emmeans(mod, ~ Inoc.treatment)
multcomp::cld(posthoc, Letters=letters)
```


### Sizing and fecundity

```{r sizing}
sz.eg<-read.csv("data/sizing_eggs.csv")
str(sz.eg)

sz.eg$Inoc.treatment<- factor(sz.eg$Inoc.treatment, levels=c("L+", "L-", "H+", "H-", "LP+", "LP-"))
sz.eg$Inoc.plank.nutr.source<- factor(sz.eg$Inoc.plank.nutr.source, levels=c("L+", "H+", "LP+"))
sz.eg$Bottle.color<- factor(sz.eg$Bottle.color)
sz.eg$Bottle.number<- factor(sz.eg$Bottle.number)
sz.eg$Bottle.ID<- factor(sz.eg$Bottle.ID)

# make factor levels
col.fac<-c("Inoc.plank.nutr.source", "Inoc.treatment")
sz.eg[col.fac]<-lapply(sz.eg[col.fac], factor) # make all these factors

make.num<-c("size..mm", "egg.number", "young.number", "egg.and.young", "individuals.w.eggs", 
            "individuals.w.young", "fecund.indiv", "no.fecund.indiv", "all.indiv")

sz.eg[make.num] <- lapply(sz.eg[make.num], as.numeric) # make all these numeric
```


```{r size histograms}
########## size histograms
# across all treatments
size.hist.all<-ggplot(sz.eg, aes(x = size..mm, y = Inoc.treatment, fill = Inoc.plank.nutr.source)) +
  geom_density_ridges(alpha=0.4, scale = 1) +
  scale_y_discrete(expand = c(0, 1.2))+
  xlab("size (mm)") +
  xlim(0,3.5)+
  ylab("Inoc. Treatment")+
  theme_ridges() +
  theme(legend.position = "top") +
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source")


# from the Low treatment
sz.eg.L<-sz.eg[(sz.eg$Inoc.plank.nutr.source=="L+"),]
size.hist.L<-ggplot(sz.eg.L, aes(x = size..mm, y = Inoc.treatment, fill = Inoc.plank.nutr.source)) +
  geom_density_ridges(alpha=0.4, scale = 1) +
  scale_y_discrete(expand = c(0, 1.2))+
  xlim(0,3.5)+
  xlab("size (mm)") +
  ylab("Inoc. Treatment")+
  theme_ridges() +
  theme(legend.position = "top") +
  scale_fill_manual(values="lightskyblue",
                    name = "Plankton source")

# from the High treatment
sz.eg.H<-sz.eg[(sz.eg$Inoc.plank.nutr.source=="H+"),]
size.hist.H<-ggplot(sz.eg.H, aes(x = size..mm, y = Inoc.treatment, fill = Inoc.plank.nutr.source)) +
  geom_density_ridges(alpha=0.4, scale = 1) +
  scale_y_discrete(expand = c(0, 1.2))+
  xlim(0,3.5)+
  xlab("size (mm)") +
  ylab("Inoc. Treatment")+
  theme_ridges() +
  theme(legend.position = "top") +
  scale_fill_manual(values="palegreen3",
                    name = "Plankton source")

#
sz.eg.LP<-sz.eg[(sz.eg$Inoc.plank.nutr.source=="LP+"),]
size.hist.LP<-ggplot(sz.eg.LP, aes(x = size..mm, y = Inoc.treatment, fill = Inoc.plank.nutr.source)) +
  geom_density_ridges(alpha=0.4, scale = 1) +
  scale_y_discrete(expand = c(0,1.2))+
  xlab("size (mm)") +
  ylab("Inoc. Treatment")+
  xlim(0,3.5)+
  theme_ridges() +
  theme(legend.position = "top") +
  scale_fill_manual(values="lightsalmon3",
                    name = "Plankton source")

### combine plots
size.distrib<-plot_grid(
  size.hist.L,
  size.hist.H,
  size.hist.LP,
  rel_widths = c(8,8,8), ncol=3)

ggsave("figures/size.histograms.pdf", height=6, width=10)

```


```{r size cutoff}
##### try to find bimodal cutoff
sz.eg.no.NA<-na.omit(sz.eg) 
# Estimating the parameters of the finite mixture model:
size_out <- em(sz.eg.no.NA$size..mm,"normal","normal")
# Adding the E-M estimated finite mixture model:


hist(sz.eg.no.NA$size..mm, probability=TRUE, ylim=c(0,3), col="gold2",
     main="Daphnia size distribution",
     xlab="size (mm)")
lines(size_out,lwd=1.5,col="coral")
# Estimating a cutoff value from this fitted finite mixture model:
cut_off <- cutoff(size_out)
#polygon(c(cut_off[-1],rev(cut_off[-1])),c(0, 0, 0.55, 0.55), col=rgb(0,0,1, 0.2),border=NA)
abline(v=cut_off[-1],lty=2,col="cornflowerblue") # 1.35 mm cutoff
abline(v=cut_off[1],col="cornflowerblue")

dev.copy(pdf, "figures/hist.size.cutoff.pdf", height=6, width=5)
dev.off() 



## add column for juvenile/adults to sz.eg df.
# if >= 1.35 mm then call it an adult, if < call it a juvenile, and if NA then NA
sz.eg$adult<-as.numeric(ifelse(sz.eg$size..mm >= 1.35, 1,
                               ifelse(is.na(sz.eg$size..mm) == TRUE, NA, 0)))

sz.eg$juvenile<-as.numeric(ifelse(sz.eg$size..mm < 1.35, 1,
                                  ifelse(is.na(sz.eg$size..mm) == TRUE, NA, 0)))

# make factor level for "juvenile or adult"
sz.eg$size.class<-as.factor(ifelse(sz.eg$adult == 1, "adult",
                        ifelse(sz.eg$juvenile == 1, "juvenile", NA)))


```


```{r size by groups}

########## size by groups (all individuals)
size.all<- ggplot(sz.eg, aes(y=size..mm, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("All Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.2) +
  ylim(0,3.5)+
  xlab("Inoculation Water Treatment") +
  ylab("size (mm)")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()


########## size by juveniles
#subset
juv<-na.omit(sz.eg[(sz.eg$size.class=="juvenile"),])
juv$Inoc.treatment<- factor(juv$Inoc.treatment, levels=c("L+", "L-", "H+", "H-", "LP+", "LP-"))
juv$Inoc.plank.nutr.source<- factor(juv$Inoc.plank.nutr.source, levels=c("L+", "H+", "LP+"))

size.juveniles<- ggplot(juv, aes(y=size..mm, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("Juvenile Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.2) +
  ylim(0,3.5)+
  xlab("Inoculation Water Treatment") +
  ylab("juvenile size (mm)")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()


########## size by adults
#subset
adul<-na.omit(sz.eg[(sz.eg$size.class=="adult"),])
adul$Inoc.treatment<- factor(adul$Inoc.treatment, levels=c("L+", "L-", "H+", "H-", "LP+", "LP-"))
adul$Inoc.plank.nutr.source<- factor(adul$Inoc.plank.nutr.source, levels=c("L+", "H+", "LP+"))

size.adult<- ggplot(adul, aes(y=size..mm, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("Adult Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.2) +
  ylim(0,3.5)+
  xlab("Inoculation Water Treatment") +
  ylab("adult size (mm)")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

# get the legend
extract.legend <- get_legend(
  # create some space to the left of the legend
  size.all + theme(legend.box.margin = margin(0, 0, 0, 10)))

# combine the plots
size.classes<-plot_grid(
  size.all+ theme(legend.position = "none"),
  size.adult+ theme(legend.position = "none"),
  size.juveniles + theme(legend.position = "none"), extract.legend,
  rel_widths = c(8,8,8,4), ncol=4)

ggsave("figures/size.classes.pdf", height=6, width=10)




#### make summary dataframes
### count of classes
indiv.sum<-aggregate(all.indiv~ 
                       Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sum)
juv.sum<-aggregate(juvenile~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, 
                     data=sz.eg, sum)
adult.sum<-aggregate(adult~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, 
                     data=sz.eg, sum)

df.class<-cbind(indiv.sum, juv.sum[4], adult.sum[4])
colnames(df.class)[4]<-"indiv.sum"
colnames(df.class)[5]<-"juv.sum"
colnames(df.class)[6]<-"adult.sum"

########## total number in each group
total.plot<-ggplot(df.class, aes(y=indiv.sum, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("All Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("# indiv")+
  ylim(0,150)+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

num.juv.plot<-ggplot(df.class, aes(y=juv.sum, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("Juvenile Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("# juveniles")+
  ylim(0,150)+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

num.adult.plot<-ggplot(df.class, aes(y=adult.sum, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("Adult Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("# adult")+
  ylim(0,150)+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

# combine the plots
number.classes<-plot_grid(
  total.plot+ theme(legend.position = "none"),
  num.juv.plot+ theme(legend.position = "none"),
  num.adult.plot + theme(legend.position = "none"), extract.legend,
  rel_widths = c(8,8,8,4), ncol=4)

ggsave("figures/abundance.classes.pdf", height=6, width=10)


######## proportion of classes
prop.juv.plot<-ggplot(df.class, aes(y=(juv.sum/indiv.sum), x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("Prop. Juvenile Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("prop juveniles")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

prop.adult.plot<-ggplot(df.class, aes(y=(adult.sum/indiv.sum), x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  ggtitle("Prop. Adult Daphnia")+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("prop adult")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

# combine the plots
prop.classes<-plot_grid(
  prop.juv.plot+ theme(legend.position = "none"),
  prop.adult.plot + theme(legend.position = "none"), extract.legend,
  rel_widths = c(8,8,4), ncol=3)

ggsave("figures/prop.classes.pdf", height=6, width=10)




####### mean egg number across all individuals
egg.b.mean<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, mean)
egg.b.sd<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sd)
egg.b.n<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, length)

# number of eggs in a parent, # of young in a parent, and # of young+eggs in a parent
egg.sum<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sum)
young<-aggregate(young.number~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sum)
young.egg<-aggregate(egg.and.young~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sum)

## means by bottles
df.b<-cbind(egg.b.mean, egg.b.sd[4], egg.b.n[4])
colnames(df.b)[4]<-"b.egg.mean"
colnames(df.b)[5]<-"b.sd"
colnames(df.b)[6]<-"egg.b.n"

## grand means (of all treatment bottles)
egg.mean<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg, mean)
egg.SD<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg, sd)
egg.n<-aggregate(egg.number~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg, length)

df<-cbind(egg.mean, egg.SD[3], egg.n[3])
colnames(df)[3]<-"egg.mean"
colnames(df)[4]<-"sd"
colnames(df)[5]<-"egg.n"
df$se<-(df$sd)/sqrt(df$egg.n)
  

# sum of individuals with and without eggs or young (and total parents)
indiv.sum<-aggregate(all.indiv~ Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sum)
fecund.sum<-aggregate(fecund.indiv~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, data=sz.eg, sum)
no.fecund.sum<-aggregate(no.fecund.indiv~Inoc.treatment+Inoc.plank.nutr.source+Bottle.ID, 
                         data=sz.eg, sum)

# sums
df2<-cbind(indiv.sum, fecund.sum[4], no.fecund.sum[4],
           egg.sum[4], young[4], young.egg[4])
colnames(df2)[4]<-"ind.sum"
colnames(df2)[5]<-"fecund.sum"
colnames(df2)[6]<-"no.fecund.sum"
colnames(df2)[7]<-"egg.sum"
colnames(df2)[8]<-"young.sum"
colnames(df2)[9]<-"young.egg.sum"


####################### plots
pd<-position_dodge(0.15)

########## number of fecund females
fecund<- ggplot(df2, aes(y=fecund.sum, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("# w/eggs or young")+
  ylim(0,120)+
  ggtitle("Fecund indiv.")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

######### number of indiv. w/o eggs or young
no.fecund<- ggplot(df2, aes(y=no.fecund.sum, x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("# w/o eggs or young")+
  ylim(0,120)+
  ggtitle("Non-fecund indiv.")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

### combine plots
total.fecund.plots<-plot_grid(
  fecund+ theme(legend.position = "none"),
  no.fecund + theme(legend.position = "none"), extract.legend,
  rel_widths = c(8,8,4), ncol=3)

ggsave("figures/total.fecund.pdf", height=6, width=10)



#### proportion of total individuals WITH eggs 
PROP.fecund<- ggplot(df2, aes(y=(fecund.sum/ind.sum), x=Inoc.treatment, fill=Inoc.plank.nutr.source)) +
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("prop females w/eggs or young")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

#### proportion of total individuals WITHOUT eggs 
PROP.no.fecund<- ggplot(df2, aes(y=(no.fecund.sum/ind.sum), x=Inoc.treatment, fill=Inoc.plank.nutr.source)) + 
  geom_boxplot(outlier.shape = NA, alpha=0.8)+
  geom_point(pch = 21, position = position_jitterdodge(), alpha=0.6) +
  xlab("Inoculation Water Treatment") +
  ylab("prop indiv w/o eggs or young")+
  scale_fill_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

# combine the plots
prop.fecund.plots<-plot_grid(
  PROP.fecund+ theme(legend.position = "none"),
  PROP.no.fecund + theme(legend.position = "none"), extract.legend,
  rel_widths = c(8,8,4), ncol=3)

ggsave("figures/prop.fecund.pdf", height=6, width=10)



#####################
####
sz.eg.NAs<-sz.eg
sz.eg.NAs[sz.eg.NAs==0]<-NA

eggY.mean.NA<-aggregate(egg.and.young~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg.NAs, mean)
eggY.sd.NA<-aggregate(egg.and.young~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg.NAs, sd)
eggY.n.NA<-aggregate(egg.and.young~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg.NAs, length)


## means
df3<-cbind(eggY.mean.NA, eggY.sd.NA[3], eggY.n.NA[3])
colnames(df3)[4]<-"sd"
colnames(df3)[5]<-"n"
df3$se<- df3$sd/sqrt(df3$n)


######
eggY.indiv.mean.plot<-ggplot(df3, aes(x=Inoc.treatment, y=egg.and.young, group=Inoc.plank.nutr.source, 
               color=Inoc.plank.nutr.source)) + 
  geom_errorbar(aes(ymin=egg.and.young-se, ymax=egg.and.young+se), 
                width=0.0, position=pd) +
  geom_point(position=pd, size=2.5) + 
  ylab("egg+young/parent") +
  ggtitle("number of eggs/young per fecund female") +
  scale_color_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

ggsave("figures/eggs.mean.by.indiv.pdf", height=6, width=5)


###### what is average # of young neonates, when neonates are observed?
### just number of neonate young
young.mean.NA<-aggregate(number.young~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg.NAs, mean)
young.sd.NA<-aggregate(number.young~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg.NAs, sd)
young.n.NA<-aggregate(number.young~Inoc.treatment+Inoc.plank.nutr.source, data=sz.eg.NAs, length)


## means
df4<-cbind(young.mean.NA, young.sd.NA[3], young.n.NA[3])
colnames(df4)[4]<-"sd"
colnames(df4)[5]<-"n"
df4$se<- df4$sd/sqrt(df4$n)


######
Young.indiv.mean.plot<-ggplot(df4, aes(x=Inoc.treatment, y=number.young, group=Inoc.plank.nutr.source, 
               color=Inoc.plank.nutr.source)) + 
  geom_errorbar(aes(ymin=number.young-se, ymax=number.young+se), 
                width=0.0, position=pd) +
  geom_point(position=pd, size=2.5) + 
  ylab("#young/fecund female") +
  scale_color_manual(values=c("lightskyblue", "palegreen3", "lightsalmon3"),
                    name = "Plankton source") +
  theme_classic()

```


